name: Build Paper

on: [push, pull_request]

jobs:
  build:
    name: Patch Paper

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Patch
      run: ./paper patch
