name: Build

on: [push, pull_request]

jobs:
  build:
    name: Patch

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set Credentials
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Patch
      run: ./paper patch
